version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - '5432:5432'
volumes:
  db:
    driver: local