version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5436
    ports:
      - '5436:5432'

  test-db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    expose:
      - 5437
    ports:
      - '5437:5432'

volumes:
  db:
    driver: local